### ISSUE TITLE
Metadata cache fails on R 4.0.0 (R-devel currently)

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgcache#38] opened 2020-03-03 13:28 UTC
Because there are no binaries available:
```{r}
> meta_cache_list()
✖ Metadata update failed
⠹ Updating metadata [0/12] | Downloading [6.97 kB / 181.02 kB]Error in stop(http_error(resp)) :
Not Found (HTTP 404).

Could not load or update metadata cache. If you think your local cache
is broken, try deleting it with `meta_cache_cleanup()`, or the
`$cleanup()` method.
```

It is trying to download `https://cloud.r-project.org/bin/macosx/el-capitan/contrib/4.0/PACKAGES.gz` which is 404.

**Comment by Hong-Revo** [comment] 2020-03-24 17:23
I'm currently getting [Travis failures ](https://travis-ci.org/github/RevolutionAnalytics/checkpoint/builds/666438019) with checkpoint on R-devel, I guess this is the root cause?

**Comment by Hong-Revo** [comment] 2020-03-30 10:09
This issue is actually fairly critical to the smooth functioning of checkpoint. Is it possible to get an estimate on when it will be fixed?

**Comment by Hong-Revo** [comment] 2020-04-02 21:16
Ok, probably not so critical; I've just discovered that you can specify `config=list(platforms="source")` to download the source packages instead. Would still be nice to have this as an automatic fallback when binaries are unavailable though.

**Closed** 2020-07-05 22:27 UTC
Labels: bug
